#!/bin/bash
# change working directory
pushd ~/github.com/eyereasoner/lingua

# create image
swipl -q -f lingua.pl -g "qsave_program('lingua.pvm', [goal(main)]), halt."

# link lingua command
sudo ln -sf $(realpath ./lingua) /usr/local/bin

popd
