#!/bin/bash
pushd ~/github.com/eyereasoner/lingua > /dev/null

# create image
swipl -q -f lingua.pl -g "qsave_program('lingua.pvm', [goal(main)]), halt."

# link lingua command
sudo ln -sf $(realpath ./lingua) /usr/local/bin

popd > /dev/null
